steaming-app:
  image: sashachepurnoi/streaming-app:1
  restart: always
  environment:
    KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_HOST}:9092"
    SCHEMA_REGISTRY_URL: "http://${KAFKA_HOST}:8081"
    WEATHER_TOPIC: "weather-data"
    SOLAR_DATA_TOPIC: "solar-panel-data"
    OUTPUT_TOPIC: "solar-rich"
    APP_ID: "enrich-service"
    JOIN_INTERVAL_SEC: "5"

