version: '3'
services:
  plant:
    image: sashachepurnoi/solar-plant:1
    restart: always
    environment:
      ZOOKEEPER_URL: "${KAFKA_HOST}:2181"
      KAFKA_BOOTSTRAP_SERVERS: "${KAFKA_HOST}:9092"
      SCHEMA_REGISTRY_URL: "http://${KAFKA_HOST}:8081"
      TOPIC: "solar-panel-data"
      INTERVAL_SEC: "5"
      PANEL_COUNT: "20"